<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lidar">

  <joint name="rplidar_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${chassis_height + 0.1}" rpy="0 0 3.14"/>
    <parent link="chassis_link"/>
    <child link="laser_link"/>
  </joint>

  <!-- rplidar laser_link -->
  <link name="laser_link">
    <collision>
      <origin xyz="0 0 0" rpy="1.5707 0 4.71"/>
      <geometry>
        <mesh filename="package://jackal_description_sim/meshes/rplidar.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.065" rpy="1.5707 0 4.71"/>
      <geometry>
        <mesh filename="package://jackal_description_sim/meshes/rplidar.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </visual>
    
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0.1" rpy="1.5707 0 4.71"/>
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
    </inertial>
  </link>

  <gazebo reference="laser_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

 <!-- RpLidar A2 using CPU -->
 <gazebo reference="laser_link">
  <sensor type="ray" name="rplidar_sensor">
    <pose>0 0 0.06 0 0 0</pose>
    <visualize>true</visualize>
    <alwaysOn>true</alwaysOn>
    <update_rate>5</update_rate>
    <ray>
      <scan>
        <horizontal>
          <samples>360</samples>
          <resolution>1</resolution>
          <min_angle>-3.14159265</min_angle>
          <max_angle>3.14159265</max_angle>
        </horizontal>
      </scan>
      <range>
        <min>0.2</min>
        <max>12.0</max>
        <resolution>0.01</resolution>
      </range>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.01</stddev>
      </noise>
    </ray>
    <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
          <queue_size>10000</queue_size> 
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
    </plugin>
  </sensor>
</gazebo> 

</robot>